title: PaleOrdia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the Homepage of the GigaMesh software framework.
collections:
  pages:
    output: true
    permalink: /:path/

